services:

  ui:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/ui/src:/app/src
      - ./services/ui/public:/app/public
    environment:
      - API_BASE_URI=$API_BASE_URI
      - LISTEN_PORT=$LISTEN_PORT

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/backend/src:/app/src
    ports:
      - "5678:5678" # debugger
    environment:
      - "LOG_LEVEL=INFO"

  postgres:
    ports:
      - "5432:5432" # direct access
  
  migrations:
    build:
      dockerfile: Dockerfile.dev
    user: ${MY_UID:-1000}:${MY_GID:-1000}
    volumes:
      - ./services/migrations/:/db/:rw
